# Generated by Django 5.2.7 on 2025-11-20 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code for ticket validation', null=True, upload_to='tickets/qr_codes/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
