# Generated by Django 4.1.13 on 2025-11-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_is_approved_field'),
        ('api', '0003_add_approval_status'),
    ]

    operations = [
    ]
